In [85]:
import numpy as np
import pandas as pd
form = "C:/Users/wnduq/Desktop/쇼핑인사이트/성별_연령별_쇼핑인사이트/{}대_{}성_{}.csv" 

a=np.array([1,2,3,4,5,6])
a=a*10

b=["남","여"]

c=["출산&식품","패션잡화&화장품","디지털&가구","스포츠&생활","여행&면세점"]

data=pd.DataFrame(np.zeros((365,1)))

for i in a :
    for j in b:
        for k in c:
            x=pd.read_csv(form.format(i,j,k),encoding="euc-kr")["adj_ratio"]
            y=pd.DataFrame(np.array(x[365:365+365]))
            z=pd.DataFrame(np.array(x[365+365:]))
            data=pd.concat([data,y,z],axis=1)
            

data

,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
0,0.0,8.856528,4.220584,31.290931,3.971121,61.70937,4.45898,24.307833,21.024264,3.825492,...,9.88707,21.78333,34.76486,11.32675,28.50019,20.09434,17.02434,28.01378,7.37925,0.11243
1,0.0,9.531792,4.715204,32.027645,4.401840,58.86758,4.19231,22.547461,20.567737,4.331182,...,11.89870,22.33574,37.52199,12.24090,31.60441,20.21900,18.08760,31.32088,7.74833,0.06599
2,0.0,8.624883,4.686938,31.322882,4.211361,57.17788,4.24946,21.650992,19.590783,3.986480,...,11.78138,23.62631,37.73464,12.01359,31.12045,21.46802,16.49149,31.70463,7.94876,0.11243
3,0.0,8.119201,4.736707,30.802454,4.035022,56.00983,4.03072,21.613511,19.236252,4.116742,...,11.48073,22.88570,36.32919,12.24090,29.94964,20.87895,15.67266,32.04438,7.69945,0.07332
4,0.0,7.745619,4.552991,29.140400,3.826726,53.34930,3.92012,20.070045,18.643926,3.825492,...,10.42481,22.95658,34.69153,11.57606,28.70551,20.51231,16.46705,30.38717,7.70189,0.17354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,0.0,5.486328,4.074342,28.147459,3.390476,44.01720,3.36774,19.137321,14.108752,2.400614,...,13.44104,32.49413,51.08281,17.04878,34.91396,27.98201,24.29360,37.25312,5.71714,0.10999
361,0.0,5.442083,3.884484,27.106603,3.386784,43.45806,3.32104,18.695540,14.820272,2.514897,...,12.44867,30.13541,49.49648,16.12240,34.85529,26.37123,26.96763,36.24608,6.16445,0.11732
362,0.0,6.972036,4.375420,32.948075,3.650380,54.23533,4.16712,23.725955,18.519194,2.543776,...,11.98425,29.45590,51.52522,16.85569,36.02610,30.70981,26.47389,36.78627,6.43576,0.09288
363,0.0,7.496769,4.775421,38.420890,4.157295,57.65775,5.11520,26.335479,19.668197,2.670346,...,12.63199,31.41865,52.52737,16.37905,37.90330,30.53382,26.55944,38.50459,6.77062,0.10510
364,0.0,6.114896,3.940396,30.180030,3.698310,47.53732,3.96866,19.825500,16.830107,2.375420,...,11.73494,26.56922,42.97272,14.49452,33.40340,25.95326,20.64430,33.35940,5.30651,0.06355

In [86]:
data.to_csv("C:/Users/wnduq/Desktop/merged_data.csv")